# Code formatting style (read by JuliaFormatter.jl).
# Use to avoid cluttering diffs.

# The following are already the defaults parameters,
# but this way they are explicit.
always_for_in = true
indent = 4
long_to_short_function_def = true
separate_kwargs_with_semicolon = true
trailing_comma = true
whitespace_in_kwargs = true
format_docstrings = true
