name = "EcologicalNetworksDynamics"
uuid = "2fd9189a-c387-4076-88b7-22b33b5a4388"
authors = [
    "Ismaël Lajaaiti <ismael.lajaaiti@umontpellier.fr>",
    "Iago Bonnici <iago.bonnici@umontpellier.fr>",
    "Sonia Kéfi <sonia.kefi@umontpellier.fr>",
    "Hana Mayall <hbmayall1@sheffield.ac.uk>",
    "Alain Danet <a.h.danet@sheffield.ac.uk>",
    "Andrew P Beckerman <a.beckerman@sheffield.ac.uk>",
    "Thomas Malpas <tdmalpas1@sheffield.ac.uk>",
    "Eva Delmas <eva.delmas@gmail.com>",
]
version = "0.2.0"

[deps]
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
# Decimals = "abce61dc-4473-55a0-ba07-351d65e31d42"
# DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
# DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
# DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
# Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
# Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
# Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
# LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
# Mangal = "b8b640a6-63d9-51e6-b784-5033db27bef2"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
# SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
# Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
# StringCases = "f22f4433-750e-5048-95f9-cae576f2c120"

# [compat]
# julia = "1.10"
# Crayons = "4.1"
# Decimals = "0.4"
# DiffEqBase = "6.148"
# DiffEqCallbacks = "3.4"
# DifferentialEquations = "7.13"
# Distributions = "0.25"
# Documenter = "1.3"
# Graphs = "1.9"
# MacroTools = "0.5"
# Mangal = "0.5"
# OrderedCollections = "1.6"
# SciMLBase = "2.30"
# StringCases = "0.1"
